### ISSUE TITLE
Wrong parameter definition

### ISSUE THREAD

**Issue by marcomansiwestland** [Azure/Bio-Compliancy#11]
https://github.com/Azure/Bio-Compliancy/blob/48cc443ca01d9fd0dfc00c5091b33fe386e7a315/ARM/BIO-azuredeploy.json#L3796

Hi, everywhere in the ARM/BIO-azuredeploy.json file are the parameters defined in a wrong way, with double [[

**Comment by odegroot** [comment]
Somehow these parameter references do work as intended, though.

When I use this ARM-template to deploy the initiative (policySet) definition to a management group, and then assign the initiative with some custom parameter values, then the underlying policy assignment does get the correct parameter value applied to it.

For example, for `listOfAllowedLocations` I had selected only `westeurope`, at the initiative assignment level. Then when I try and create a resource group in `northeurope` (on the allow-list by default), this does get blocked.

Perhaps this has to do with the fact that these parameters are declared at the initiative-level, rather than at the ARM-template-level.

**Comment by odegroot** [comment]
https://learn.microsoft.com/en-us/azure/azure-resource-manager/templates/template-expressions
> ## Escape characters
> To have a literal string start with a left bracket `[` and end with a right bracket `]`, but not have it interpreted as an expression, add an extra bracket to start the string with `[[`. For example, the variable:
> ```
> "demoVar1": "[[test value]"
> ```
> Resolves to `[test value]`.
